credentials:
  users:
    replicator:
      password: 'topsecret'
      roles: [replication]
    client:
      password: 'secret'
      roles: [super]

iproto:
  listen:
  - uri: 'unix/:./{{ instance_name }}.iproto'
  advertise:
    peer:
      login: 'replicator'

log:
  to: file

replication:
  failover: manual

groups:
  group-001:
    replicasets:
      replicaset-001:
        leader: instance-001
        instances:
          instance-001: {}
          instance-002: {}
          instance-003: {}
